### ISSUE TITLE
Stacking up many minecarts and walking into them causes a crash

### ISSUE THREAD

**Issue by GlowingUmbreon** [Patbox/TaterCart#8]
![image](https://user-images.githubusercontent.com/37640997/172437090-5fc5852f-33a5-47e0-857d-1832dc8cd559.png)
Making this to stack together many minecarts and walking into it with the blocks on the right will result in a crash:
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 07/06/2022, 11:53
Description: Ticking player

java.lang.IllegalArgumentException: Start element (9223367638808264704) is larger than end element (-9223372036854775808)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1120)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1081)
	at net.minecraft.class_5573.method_31777(class_5573.java:55)
	at net.minecraft.class_5573.method_31783(class_5573.java:118)
	at net.minecraft.class_5578.method_31807(class_5578.java:42)
	at net.minecraft.class_1937.method_8333(class_1937.java:620)
	at net.minecraft.class_1924.method_20743(class_1924.java:62)
	at net.minecraft.class_5423.method_20743(class_5423.java:24)
	at net.minecraft.class_1297.method_17835(class_1297.java:907)
	at net.minecraft.class_1297.method_5784(class_1297.java:634)
	at net.minecraft.class_1309.method_26318(class_1309.java:2252)
	at net.minecraft.class_1309.method_6091(class_1309.java:2197)
	at net.minecraft.class_1657.method_6091(class_1657.java:1602)
	at net.minecraft.class_1309.method_6007(class_1309.java:2648)
	at net.minecraft.class_1657.method_6007(class_1657.java:560)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_3222.method_14226(class_3222.java:478)
	at net.minecraft.class_3244.method_18784(class_3244.java:214)
	at net.minecraft.class_2535.method_10754(class_2535.java:247)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1120)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1081)
	at net.minecraft.class_5573.method_31777(class_5573.java:55)
	at net.minecraft.class_5573.method_31783(class_5573.java:118)
	at net.minecraft.class_5578.method_31807(class_5578.java:42)
	at net.minecraft.class_1937.method_8333(class_1937.java:620)
	at net.minecraft.class_1924.method_20743(class_1924.java:62)
	at net.minecraft.class_5423.method_20743(class_5423.java:24)
	at net.minecraft.class_1297.method_17835(class_1297.java:907)
	at net.minecraft.class_1297.method_5784(class_1297.java:634)
	at net.minecraft.class_1309.method_26318(class_1309.java:2252)
	at net.minecraft.class_1309.method_6091(class_1309.java:2197)
	at net.minecraft.class_1657.method_6091(class_1657.java:1602)
	at net.minecraft.class_1309.method_6007(class_1309.java:2648)
	at net.minecraft.class_1657.method_6007(class_1657.java:560)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 61930
	Entity Name: YesImAUmbreon
	Entity's Exact location: -2.57, -60.00, -2.72
	Entity's Block location: World: (-3,-60,-3), Section: (at 13,4,13 in -1,-4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 5552885183194.63, 45.42, -143423602007681.38
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:478)
	at net.minecraft.class_3244.method_18784(class_3244.java:214)
	at net.minecraft.class_2535.method_10754(class_2535.java:247)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.15.41_1
	Java Version: 17.0.3, Void
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Void
	Memory: 3214407208 bytes (3065 MiB) / 6543114240 bytes (6240 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: GP107 [GeForce GTX 1050 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7977.09
	Virtual memory used (MB): 9851.98
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Loaded Shaderpack: (off)
	QuiltedFabricAPI: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		hologram-api: Hologram API 0.2.1+1.18-pre5
		indium: Indium 1.0.3+mc1.18.2
		iris: Iris 1.2.4-build.38
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		miningcooldownfix: Mining Cooldown Fix 1.18.1-1.0.0
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		placeholder-api: Placeholder API 1.1.3+1.17.1
		polymer: Polymer (Core) 0.2.0-rc.2+1.18.2
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-rc.2+1.18.2
		quilt_base: Quilt Base API 1.1.0-beta.8+1.18.2
		quilt_block_extensions: Quilt Block Extensions API 1.1.0-beta.8+1.18.2
		quilt_client_command: Quilt Client Command API 1.1.0-beta.8+1.18.2
		quilt_command: Quilt Command API 1.1.0-beta.8+1.18.2
		quilt_crash_info: Quilt Crash Info 1.1.0-beta.8+1.18.2
		quilt_dimension: Quilt Dimension API 1.1.0-beta.8+1.18.2
		quilt_item_group: Quilt Item Group API 1.1.0-beta.8+1.18.2
		quilt_item_setting: Quilt Item Setting API 1.1.0-beta.8+1.18.2
		quilt_lifecycle_events: Quilt Lifecycle Events 1.1.0-beta.8+1.18.2
		quilt_loader: Quilt Loader 0.16.0
		quilt_networking: Quilt Networking 1.1.0-beta.8+1.18.2
		quilt_recipe: Quilt Recipe API 1.1.0-beta.8+1.18.2
		quilt_registry: Quilt Registry API 1.1.0-beta.8+1.18.2
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 1.1.0-beta.8+1.18.2
		quilt_resource_loader: Quilt Resource Loader 1.1.0-beta.8+1.18.2
		quilt_tags: Quilt Tags API 1.1.0-beta.8+1.18.2
		quilt_tooltip: Quilt Tooltip API 1.1.0-beta.8+1.18.2
		quilted_fabric_api: Quilted Fabric API 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_api_base: Quilted Fabric API Base 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 1.0.0-beta.14+0.51.1-1.18.2
		server_translations_api: Server Translations API 1.4.12+1.18.2
		sgui: sgui 1.0.2+1.18.2
		sodium: Sodium 0.4.1+build.15
		tatercart: TaterCart 1.0.0-pre.4+1.18.2
		universal-graves: Universal Graves 2.0.3+1.18.2
		xaerominimap: Xaero's Minimap 22.8.2
		xaeroworldmap: Xaero's World Map 1.22.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['YesImAUmbreon'/61930, l='ServerLevel[New World]', x=-2.57, y=-60.00, z=-2.72]]
	Data Packs: vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
```
When rejoining the world it will then have a similar crash.
```
---- Minecraft Crash Report ----
// Oops.

Time: 07/06/2022, 12:07
Description: Ticking entity

java.lang.IllegalArgumentException: Start element (9223367638808264704) is larger than end element (-9223372036854775808)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1120)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1081)
	at net.minecraft.class_5573.method_31777(class_5573.java:55)
	at net.minecraft.class_5573.method_31783(class_5573.java:118)
	at net.minecraft.class_5578.method_31807(class_5578.java:42)
	at net.minecraft.class_1937.method_8333(class_1937.java:620)
	at net.minecraft.class_1924.method_20743(class_1924.java:62)
	at net.minecraft.class_5423.method_20743(class_5423.java:24)
	at net.minecraft.class_1297.method_17835(class_1297.java:907)
	at net.minecraft.class_1297.callAdjustMovementForCollisions(class_1297.java)
	at net.minecraft.class_1688.handler$bem000$tatercart_customMoveOffRail(class_1688.java:2723)
	at net.minecraft.class_1688.method_7512(class_1688.java)
	at net.minecraft.class_1688.method_5773(class_1688.java:352)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1120)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1081)
	at net.minecraft.class_5573.method_31777(class_5573.java:55)
	at net.minecraft.class_5573.method_31783(class_5573.java:118)
	at net.minecraft.class_5578.method_31807(class_5578.java:42)
	at net.minecraft.class_1937.method_8333(class_1937.java:620)
	at net.minecraft.class_1924.method_20743(class_1924.java:62)
	at net.minecraft.class_5423.method_20743(class_5423.java:24)
	at net.minecraft.class_1297.method_17835(class_1297.java:907)
	at net.minecraft.class_1297.callAdjustMovementForCollisions(class_1297.java)
	at net.minecraft.class_1688.handler$bem000$tatercart_customMoveOffRail(class_1688.java:2723)
	at net.minecraft.class_1688.method_7512(class_1688.java)
	at net.minecraft.class_1688.method_5773(class_1688.java:352)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: minecraft:minecart (net.minecraft.class_1695)
	Entity ID: 6
	Entity Name: Minecart
	Entity's Exact location: -2.50, -60.00, -2.93
	Entity's Block location: World: (-3,-60,-3), Section: (at 13,4,13 in -1,-4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 2.74, -0.04, 2.74
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 13585 game time, 13585 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 69859 (now: false), thunder time: 89427 (now: false)
	Known server brands: quilt
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.15.41_1
	Java Version: 17.0.3, Void
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Void
	Memory: 1763900416 bytes (1682 MiB) / 4672454656 bytes (4456 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: GP107 [GeForce GTX 1050 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7977.09
	Virtual memory used (MB): 7361.98
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Loaded Shaderpack: (off)
	QuiltedFabricAPI: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		hologram-api: Hologram API 0.2.1+1.18-pre5
		indium: Indium 1.0.3+mc1.18.2
		iris: Iris 1.2.4-build.38
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		miningcooldownfix: Mining Cooldown Fix 1.18.1-1.0.0
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		placeholder-api: Placeholder API 1.1.3+1.17.1
		polymer: Polymer (Core) 0.2.0-rc.2+1.18.2
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-rc.2+1.18.2
		quilt_base: Quilt Base API 1.1.0-beta.8+1.18.2
		quilt_block_extensions: Quilt Block Extensions API 1.1.0-beta.8+1.18.2
		quilt_client_command: Quilt Client Command API 1.1.0-beta.8+1.18.2
		quilt_command: Quilt Command API 1.1.0-beta.8+1.18.2
		quilt_crash_info: Quilt Crash Info 1.1.0-beta.8+1.18.2
		quilt_dimension: Quilt Dimension API 1.1.0-beta.8+1.18.2
		quilt_item_group: Quilt Item Group API 1.1.0-beta.8+1.18.2
		quilt_item_setting: Quilt Item Setting API 1.1.0-beta.8+1.18.2
		quilt_lifecycle_events: Quilt Lifecycle Events 1.1.0-beta.8+1.18.2
		quilt_loader: Quilt Loader 0.16.0
		quilt_networking: Quilt Networking 1.1.0-beta.8+1.18.2
		quilt_recipe: Quilt Recipe API 1.1.0-beta.8+1.18.2
		quilt_registry: Quilt Registry API 1.1.0-beta.8+1.18.2
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 1.1.0-beta.8+1.18.2
		quilt_resource_loader: Quilt Resource Loader 1.1.0-beta.8+1.18.2
		quilt_tags: Quilt Tags API 1.1.0-beta.8+1.18.2
		quilt_tooltip: Quilt Tooltip API 1.1.0-beta.8+1.18.2
		quilted_fabric_api: Quilted Fabric API 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_api_base: Quilted Fabric API Base 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 1.0.0-beta.14+0.51.1-1.18.2
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 1.0.0-beta.14+0.51.1-1.18.2
		server_translations_api: Server Translations API 1.4.12+1.18.2
		sgui: sgui 1.0.2+1.18.2
		sodium: Sodium 0.4.1+build.15
		tatercart: TaterCart 1.0.0-pre.4+1.18.2
		universal-graves: Universal Graves 2.0.3+1.18.2
		xaerominimap: Xaero's Minimap 22.8.2
		xaeroworldmap: Xaero's World Map 1.22.0
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
```

**Comment by GlowingUmbreon** [comment]
I tried stacking 10 and got launched multiple chunks away, not sure if this is related.

**Comment by GlowingUmbreon** [comment]
When there are 40 stacked and you walk into them the TPS will be reduced significantly while the karts move. And after 4 minutes it began having the same errors as mentioned before.
